apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  serviceRef:
    name: ingress-nginx-controller
    port: 80
  targetGroupARN: HTTP_ARN
  # aws_lb_target_group.http.arn
  # same as target group attachment
# ---
# apiVersion: elbv2.k8s.aws/v1beta1
# kind: TargetGroupBinding
# metadata:
#   name: ingress-nginx-controller
#   namespace: ingress-nginx
# spec:
#   serviceRef:
#     name: ingress-nginx-controller
#     port: 443
#   targetGroupARN: HTTP_ARN