apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techlog
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/choigonyok/argocd-apps'
    path: techlog
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true