apiVersion: batch/v1
kind: Job
metadata:
  name: init-job-for-backend
spec:
  template:
    spec:
      containers:
      - name: init-container
        image: achoistic98/blog_init:latest
      restartPolicy: Never
  completions: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template: 
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: achoistic98/blog_backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST_READ
          value: mysql-ha-haproxy:3306
        - name: DB_HOST_WRITE
          value: mysql-ha-0
        - name: DB_DRIVER
          value: mysql
        - name: HOST
          value: www.choigonyok.com
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: password
        - name: DB_NAME
          value: blogdb
        - name: BLOG_ID
          value: choigonyok
        - name: BLOG_PW
          value: devops
        # - name: AWS_SECRET_KEY
        #   value: 
        # - name: AWS_ACCESS_KEY
        #   value: 
        # - name: GITHUB_TOKEN
        #   value: 
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - backend
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP