apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template: 
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - backend
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: backend
        image: achoistic98/blog_backend:latest
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: backend-volume
            mountPath: /assets
        env:
        - name: DB_HOST
          value: database
        - name: ORIGIN
          value: "http://frontend"
        - name: DB_DRIVER
          value: mysql
        - name: HOST
          value: www.choigonyok.com
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: password
        - name: DB_NAME
          value: blogdb
        - name: BLOG_ID
          value: choigonyok
        - name: BLOG_PW
          value: devops
      volumes:
        - name: backend-volume        
          hostPath:
            path: /volumes
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP