apiVersion: batch/v1
kind: Job
metadata:
  name: init-job-for-backend
spec:
  template:
    spec:
      containers:
      - name: init-container
        image: achoistic98/blog_init:latest
      restartPolicy: Never
  completions: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template: 
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: achoistic98/blog_backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST_READ
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: db-host-read
              optional: false
        - name: DB_HOST_WRITE
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: db-host-write
              optional: false
        - name: DB_DRIVER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: db-driver
              optional: false
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: host
              optional: false
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: db-user
              optional: false
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: db-password
              optional: false
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: db-name
              optional: false
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: aws-secret-key
              optional: false
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: aws-access-key
              optional: false
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: github-token
              optional: false
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - backend
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP