apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ha
spec:
  serviceName: mysql-ha
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: achoistic98/blog_database:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: database-volume
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "blogdb"
      volumes:
        - name: database-volume
          hostPath:
            path: /volumes # Replace with the actual path on your host machine
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-ha-0
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mysql-ha-0
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-ha-1
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mysql-ha-1
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-ha-2
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mysql-ha-2
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP