apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: devops-system
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: FILE_SYSTEM_ID
  directoryPerms: "777"
  basePath: "/dynamic_provisioning"
  subPathPattern: ""
  ensureUniqueDirectory: "false"
  reuseAccessPoint: "false"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins-ha
  namespace: devops-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
  template: 
    metadata:
      labels:
        app.kubernetes.io/name: jenkins
      name: jenkins
      namespace: devops-system
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                - jenkins
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: jenkins
      securityContext: # .spec level securityContext
        fsGroup: 1000
      containers:
      - name: jenkins-master
        image: achoistic98/blog_jenkins:latest
        ports:
        - containerPort: 8080
        - containerPort: 50000
        securityContext: # .spec.containers level securityContext
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          # limits:
          #   memory: "1024Mi"
          #   cpu: "2000m"
        volumeMounts:
          - name: jenkins
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkins
          persistentVolumeClaim:
            claimName: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-ha-0
  namespace: devops-system
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: "external"
  #   service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
  #   service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    statefulset.kubernetes.io/pod-name: jenkins-ha-0
  ports:
    - name: ui
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: controller
      protocol: TCP
      port: 50000
      targetPort: 50000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-ha-1
  namespace: devops-system
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: "external"
  #   service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
  #   service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    statefulset.kubernetes.io/pod-name: jenkins-ha-1
  ports:
    - name: ui
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: controller
      protocol: TCP
      port: 50000
      targetPort: 50000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-ha-2
  namespace: devops-system
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: "external"
  #   service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
  #   service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    statefulset.kubernetes.io/pod-name: jenkins-ha-2
  ports:
    - name: ui
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: controller
      protocol: TCP
      port: 50000
      targetPort: 50000
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: devops-system
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins
  namespace: devops-system
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rb-jenkins
  namespace: devops-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: devops-system