apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - database-deployment
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: backend-deployment
        image: achoistic98/blog_backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: database-service
        - name: ORIGIN
          value: "http://frontend-service"
        - name: DB_DRIVER
          value: mysql
        - name: HOST
          value: <DOMAIN FOR COOKIE>
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: password
        - name: DB_NAME
          value: blog
        - name: BLOG_ID
          value: choigonyok
        - name: BLOG_PW
          value: devops