apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-csi-pv
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-048874aff96ef0a63
    volumeAttributes:
      fsType: ext4